# Generated by Django 5.2.1 on 2025-05-18 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_uploadeddataset_staff_alter_uploadeddataset_user"),
        ("clients", "0004_client_password_staff_delete_logininfo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadeddataset",
            name="user",
        ),
        migrations.AddField(
            model_name="uploadeddataset",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="uploadeddataset",
            name="staff",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.staff",
            ),
            preserve_default=False,
        ),
    ]
