# Generated by Django 5.1.7 on 2025-04-20 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("company_id", models.IntegerField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=50)),
                ("company_address", models.TextField()),
                ("company_contact_no", models.CharField(max_length=30)),
                ("company_email", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("feedback_id", models.IntegerField(primary_key=True, serialize=False)),
                ("feedback_date", models.DateField()),
                ("feedback_score", models.IntegerField()),
                (
                    "client_complaints",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginInfo",
            fields=[
                (
                    "business_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("passcode_hash", models.TextField()),
                ("email", models.CharField(max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "subscription_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("plan_type", models.CharField(max_length=30)),
                ("monthly_charges", models.FloatField()),
                ("total_charges", models.FloatField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("active", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
            ],
        ),
    ]
