# Generated by Django 5.1.7 on 2025-04-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logininfo",
            name="email",
        ),
        migrations.AlterField(
            model_name="client",
            name="company_contact_no",
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name="client",
            name="company_email",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("standard", "Standard"),
                    ("partner", "Partner"),
                ],
                max_length=30,
            ),
        ),
    ]
