# Generated by Django 5.1.7 on 2025-05-18 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_remove_logininfo_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logininfo",
            name="business_id",
        ),
        migrations.RemoveField(
            model_name="logininfo",
            name="passcode_hash",
        ),
        migrations.AddField(
            model_name="logininfo",
            name="password",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="company_email",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="logininfo",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="clients.client",
            ),
        ),
    ]
