# Generated by Django 5.1.7 on 2025-05-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_remove_logininfo_business_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="password",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "staff_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="LoginInfo",
        ),
    ]
