# Generated by Django 5.2.1 on 2025-05-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_client_password_staff_delete_logininfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="password",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
